# Generated by Django 5.1.4 on 2025-04-30 08:37

import ckeditor.fields
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ProductsTypeNames',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_shop', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(default='قم', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_persian', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_category', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_category', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-is_category', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('primary_image', models.ImageField(upload_to=utils.get_file_path)),
                ('description_brif', models.TextField(default='')),
                ('description_full', ckeditor.fields.RichTextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('is_sale', models.BooleanField(default=False)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('date_on_sale_from', models.DateTimeField(blank=True, null=True)),
                ('date_on_sale_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('seller', models.ManyToManyField(related_name='products', to='products.seller')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('img_l', models.ImageField(blank=True, null=True, upload_to='', verbose_name='low_quality')),
                ('img_m', models.ImageField(blank=True, null=True, upload_to='', verbose_name='medium_quality')),
                ('img_h', models.ImageField(blank=True, null=True, upload_to='', verbose_name='high_quality')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
                ('product_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_name', to='products.producttypename')),
            ],
            options={
                'verbose_name_plural': 'ProductImages',
            },
        ),
    ]
